openapi: 3.0.0
info:
  title: Categories POC
  description: >-
    Get or set categories that have been assigned to the active categories
    field.
  version: '2'
servers:
  - url: 'http://{server}/v1/categorizableObject'
    variables:
      server:
        default: api.example.org
paths:
  /categories:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/categories'
    post:
      requestBody:
        description: A request body.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/category'
  '/categories/{categoryId}':
    delete:
      parameters:
        - in: path
          name: categoryId
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: >-
            Delete operation successful for category resource with given id. No
            content is returned.
        '404':
          description: >-
            Delete operation failed. Category resource with the specified id not
            found.
components:
  schemas:
    category:
      type: object
      properties:
        id:
          type: integer
          format: int32
        displayname:
          type: string
    categories:
      type: array
      items:
        $ref: '#/components/schemas/category'
    requestBody:
      type: string
